### ISSUE TITLE
Migrate Element Templates

### ISSUE THREAD

**Issue by barmac** [bpmn-io/bpmn-properties-panel#109]
# Migrate Element Templates

This is an epic issue to track the element templates migration.

Miro board: https://miro.com/app/board/o9J_lxGbk7Y=/

## Backend

* [x] https://github.com/bpmn-io/bpmn-properties-panel/issues/121
  * [x] Element Templates API (loader)
  * [x] Commands
  * [x] Validator
* [x] https://github.com/camunda/element-templates-json-schema/issues/31
  * [x] Decide on the future of entriesVisible
    * We will support `entriesVisible=all` (but not for specific sections). See [solution sketch](https://miro.com/app/board/o9J_lv1HCjc=/)
  * [x] Migrate entriesVisible (based on decision)
    * [x] Update element-templates-json-schema to allow entriesVisible to be `all` or undefined / also remove deprecation
  * [x] Remove scope_old
    * [x] Investigate if a meaningful error message can be shown (using element-templase-json-schema)
* [x] https://github.com/bpmn-io/element-templates-validator/issues/2
* [x] Update `element-templates-validator` to v0.3.0

## UI

* [x] #132
  * [x] Fire an event per default which will be handled in Camunda Modeler
* [x] #145
* [x] #149
* [x] Template not found
* [x] Update available
* [x] #156
* [x] #139
* [x] #147
* [x] [UI Bug](https://github.com/bpmn-io/bpmn-properties-panel/issues/158)
* [x] [Update logic bug](https://github.com/bpmn-io/bpmn-properties-panel/issues/165)
* [x] [Error group label bug](https://github.com/bpmn-io/bpmn-properties-panel/issues/166)
* [x] [Description not rendered](https://github.com/bpmn-io/bpmn-properties-panel/issues/167)
* [x] [Cannot set custom props to undefined](https://github.com/bpmn-io/bpmn-properties-panel/issues/168)
* [x] https://github.com/bpmn-io/bpmn-properties-panel/issues/171
* [x] https://github.com/bpmn-io/bpmn-properties-panel/issues/177
* [x] https://github.com/bpmn-io/bpmn-properties-panel/issues/186

**Comment by barmac** [comment]
@philippfromme and I just had a meeting on the next steps. We decided that:
* @barmac will continue work on the template group
* @philippfromme will work on the custom properties UI

**Comment by MaxTru** [comment]
Discussion during Weekly on 02.11.: evaluate to schedule a 1/2 integration testing.

**Comment by barmac** [comment]
Status update:

Out of the todos, for these we have PRs:

-  Update logic bug
-  Error group label bug
-  Cannot set custom props to undefined

EntriesVisible handling has to be fixed yet. The custom property description is missing. We also need to implement re-render on templates being changed.

**Comment by barmac** [comment]
With each of the tasks done, I am closing this issue. Thanks @bpmn-io/modeling for making this happen.

**Comment by MaxTru** [comment]
Thanks @barmac :-)
