### ISSUE TITLE
Add Zeebe related properties

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/bpmn-properties-panel#3]
__What should we do?__

The current list of properties is very limited, not complete, and finally implemented (e.g. name properties) for the Zeebe Properties panel use case. We need to conclude them. You can find a dedicated list of the properties in [this list](https://docs.google.com/spreadsheets/d/1ixPsXqlw9qBkk-27V2PuzWRLwQ_gHw4dCiyBUoXChic/edit#gid=0). Noticeable in this regard that we will add the _documentation_ property as well for this properties panel.

Preferably we can re-use most of the getter/setter/test cases from the existing [Zeebe Properties Provider](https://github.com/camunda/camunda-bpmn-js/tree/main/lib/camunda-cloud/features/properties-provider) and wrap them into the new architecture.

**General tasks**
* [x] Decide where to store the properties (this project vs. camunda-bpmn-js) => we will add in this project, replace in camunda-bpmn-js later on
* [x] Think about strategy to re-use test cases (cf. 48d3fd70ecde57c4f6f1843e62ca2da94821aa9b)
* [x] Decide on testing environment (old style in the DOM vs. preact shallow rendering vs. ...) (cf. https://github.com/bpmn-io/properties-panel-next/pull/16)

_out of scope / to be clarified later_
* validation

**BPMN properties**
* [x] ID (group: General) @pinussilvestrus (cf. https://github.com/bpmn-io/properties-panel-next/pull/21)
  * follow up: https://github.com/bpmn-io/properties-panel-next/issues/27
* [x] Name (group: General) @pinussilvestrus  (cf. https://github.com/bpmn-io/properties-panel-next/pull/21)
* [x] Documentation (group: Documentation) @pinussilvestrus (cf. https://github.com/bpmn-io/properties-panel-next/pull/21)
* [x] Process ID + Name (group: General) for participants @barmac (cf. https://github.com/bpmn-io/properties-panel-next/pull/16)
* [x] Executable (group: General)  @pinussilvestrus (cf. https://github.com/bpmn-io/properties-panel-next/issues/29)
* [x] Errors  (group: Error)  (cf. https://github.com/bpmn-io/properties-panel-next/issues/38) @pinussilvestrus 
* [x] Messages (group: Message) (cf. https://github.com/bpmn-io/properties-panel-next/issues/38) @pinussilvestrus

**Zeebe properties**
* [x] Task definition (group: Task Definition) @pinussilvestrus (cf. bpmn-io/properties-panel-next#22)
* [x] Multi instance properties (group: Multi Instance) @pinussilvestrus (cf. bpmn-io/properties-panel-next#22)
* [x] Inputs + Outputs (groups: Input & Output) @pinussilvestrus 
* [x] Condition expression (group: Condition) @MaxTru (cf. https://github.com/bpmn-io/properties-panel-next/issues/28)
* [x] Headers (group: Header) @pinussilvestrus (cf. https://github.com/bpmn-io/properties-panel-next/issues/34)
* [x] Call activity process id (group: Target) @MaxTru (cf. https://github.com/bpmn-io/properties-panel-next/issues/39)
* [x] Call activity propagate all children @MaxTru (cf. https://github.com/bpmn-io/properties-panel-next/issues/42)
* [x] Message subscription correlation key (cf. https://github.com/bpmn-io/properties-panel-next/issues/50) @pinussilvestrus  
* [x] Form JSON configuration (group: Forms)  @nikku (cf. bpmn-io/properties-panel-next#49) 
* [x] Timer Definition (group: Timer Definition) @MaxTru (cf. #4)

__Why should we do it?__

Child of https://github.com/bpmn-io/internal-docs/issues/256

**Comment by MaxTru** [comment]
:tada: All properties were implemented - closing this :-) Great job!
